spring:
  application:
    name: mitia
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: "${DB_CONN_STRING}"
    driverClassNname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
        default_schema: public